// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnLfkbYu-e2csyyqRgmOFxBLY4NRfnt4',
    appId: '1:297062883071:web:20dacf591522f77a9836ca',
    messagingSenderId: '297062883071',
    projectId: 'e-commerce-app-1395a',
    authDomain: 'e-commerce-app-1395a.firebaseapp.com',
    storageBucket: 'e-commerce-app-1395a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_9tNvcqp5uEvvqhIqTp0FBLm6sKh5gRI',
    appId: '1:297062883071:android:29125a1e24cb419a9836ca',
    messagingSenderId: '297062883071',
    projectId: 'e-commerce-app-1395a',
    storageBucket: 'e-commerce-app-1395a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszABI-rXM3HHVc7I7CijeB312TLoxOqs',
    appId: '1:297062883071:ios:cbc225a32b2ad5039836ca',
    messagingSenderId: '297062883071',
    projectId: 'e-commerce-app-1395a',
    storageBucket: 'e-commerce-app-1395a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszABI-rXM3HHVc7I7CijeB312TLoxOqs',
    appId: '1:297062883071:ios:cbc225a32b2ad5039836ca',
    messagingSenderId: '297062883071',
    projectId: 'e-commerce-app-1395a',
    storageBucket: 'e-commerce-app-1395a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKnLfkbYu-e2csyyqRgmOFxBLY4NRfnt4',
    appId: '1:297062883071:web:01045918f0e850119836ca',
    messagingSenderId: '297062883071',
    projectId: 'e-commerce-app-1395a',
    authDomain: 'e-commerce-app-1395a.firebaseapp.com',
    storageBucket: 'e-commerce-app-1395a.firebasestorage.app',
  );
}
